---

- name: Collect IOS facts
  hosts: cisco_routers
  gather_facts: false
  connection: network_cli


  tasks:

    - name: Facts
      ios_facts:
        gather_subset: all


    - name: Show ansible_net_interfaces fact
      debug: var=ansible_net_interfaces
