#!/usr/bin/env python

def send_show_command(device='devices.yaml', command='show clock'):
    import netmiko, yaml, logging

    logging.basicConfig(level=logging.INFO)

    with open(device) as f:
        dev = yaml.safe_load(f)


    for device_params in dev:
        my_con = netmiko.ConnectHandler(**device_params)
        logging.info('turn enable on')
        my_con.enable()
        logging.info('send command')
        result = my_con.send_command(command)
        print(result)



if __name__ == "__main__":
    send_show_command()
